version: '3.7'

services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        command: npm start
        volumes: 
            - /app/node_modules
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: npm run test
        volumes: 
            - /app/node_modules
            - .:/app
    